GET https://9lvlmz-3000.csb.app/params/Miguel HTTP/1.1

###

GET https://9lvlmz-3000.csb.app/ HTTP/1.1

###

POST https://9lvlmz-3000.csb.app/ HTTP/1.1
content-type: application/json

{
    "name": "sample"
}